# Generated by Django 5.0.3 on 2024-12-21 11:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs_app', '0002_alter_club_about_alter_club_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='clubs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='club',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='club',
            name='background_color',
            field=models.CharField(default='#0095ff', max_length=255),
        ),
    ]
