"""
Django settings for clubs_project project.

Generated by 'django-admin startproject' using Django 5.0.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import os
from .middleware import Custom404Middleware
# from clubs_app.club_routers import ClubsAppRouter

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-r@03p=u^axv4h!i3tp&b=$%0gph$^o+!*+b$12c=-uwj8$far*'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
# using gcloud database then G_CLOUD_SQL_DB = True else using at localhost (ex. xampp) G_CLOUD_SQL_DB = false
G_CLOUD_SQL_DB = False
G_CLOUD_STORAGE_IMAGES = True
# using localhost to run RUN_AT_LOCALHOST = True, if using in server RUN_AT_LOCALHOST = False
RUN_AT_LOCALHOST = True

if RUN_AT_LOCALHOST == False:
    APPEND_SLASH = True
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SECURE_SSL_REDIRECT = True
    PASSWORD_RESET_ALLOWED_HOSTS = 'http://clubs.pes.edu'

# ALLOWED_HOSTS = ['*']
ALLOWED_HOSTS = [
    f'clubs.pes.edu',
    f'www.clubs.pes.edu',
    f'clubs-service-dot-focus-copilot-438910-g0.el.r.appspot.com',
    f'clubs-v1-dot-clubs-service-dot-focus-copilot-438910-g0.el.r.appspot.com',
    f'clubs-v2-dot-clubs-service-dot-focus-copilot-438910-g0.el.r.appspot.com',
    f'test-cash-v1-dot-clubs-service-dot-focus-copilot-438910-g0.el.r.appspot.com',
    f'127.0.0.1'
    ]


# Application definition

INSTALLED_APPS = [
    'whitenoise.runserver_nostatic',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'rest_framework',
    'clubs_app',
    'storages',
    'ckeditor',
]

MIDDLEWARE = [
    'clubs_project.middleware.Custom404Middleware',
    'django.middleware.security.SecurityMiddleware',
    # custom middelware
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'clubs_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR / 'templates',
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
            'libraries': {
                'custom_tags': 'clubs_app.templatetags.club_custom_tags',
            },
        },
    },
]

WSGI_APPLICATION = 'clubs_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

if G_CLOUD_SQL_DB == True:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'HOST': '/cloudsql/focus-copilot-438910-g0:asia-south1:django-apps-db',
            'NAME': 'clubs_app_2024_02_09',
            'USER': 'django-apps-user',
            'PASSWORD': '/h8v64^UPjEj+lDT',
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'HOST': 'localhost',
            'NAME': 'clubs_app_2024_02_09',
            'USER': 'root',
            'PASSWORD': '',
            'PORT': '3306',
            'OPTIONS': {
            'charset': 'utf8mb4',
            },
        }
    }
    
# to store caches
# CACHES = {
#     'default': {
#         'BACKEND': 'django_redis.cache.RedisCache',
#         'LOCATION': 'redis://10.186.68.203:6378/1',
#         'OPTIONS': {
#             'CLIENT_CLASS': 'django_redis.client.DefaultClient',
#             'SOCKET_CONNECT_TIMEOUT': 5,  # Increase if necessary
#             'SOCKET_TIMEOUT': 5,           # Increase if necessary
#         },
#         'TIMEOUT': 300,  # Cache timeout in seconds (5 minutes)
#     }
# }


# CACHES = {
#     'default': {
#         'BACKEND': 'django_redis.cache.RedisCache',
#         'LOCATION': 'redis://127.0.0.1:6379/1',  # Redis is running on localhost (127.0.0.1)
#         'OPTIONS': {
#             'CLIENT_CLASS': 'django_redis.client.DefaultClient',
#         },
#         'TIMEOUT': 300,  # Cache timeout in seconds (5 minutes)
#     }
# }


# DATABASE_ROUTERS = ['ClubsAppRouter', 'path.to.StaffAppRouter']


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
    
]




# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

# Set the GOOGLE_APPLICATION_CREDENTIALS environment variable
os.environ['GOOGLE_APPLICATION_CREDENTIALS'] = os.path.join(BASE_DIR, 'credential.json')
from google.oauth2 import service_account
GS_CREDENTIALS = service_account.Credentials.from_service_account_file(os.path.join(BASE_DIR, 'credential.json'))

from google.cloud import storage

# Set the Google Cloud Storage bucket name
BUCKET_NAME = 'focus-copilot-438910-g0.appspot.com'

# Set the default storage class to use Google Cloud Storage
DEFAULT_FILE_STORAGE = 'storages.backends.gcloud.GoogleCloudStorage'

# Configure the Google Cloud Storage settings
GS_BUCKET_NAME = BUCKET_NAME  # Replace with your bucket name
GS_BUCKET_LOCATION = 'asia-south1'  # Replace with your bucket location
GS_PROJECT_ID = 'focus-copilot-438910-g0'  # Replace with your project ID

AUTH_USER_MODEL = 'clubs_app.ClubUser'

STATIC_URL = '/static/'

if G_CLOUD_STORAGE_IMAGES == True:

    STATIC_ROOT = BASE_DIR / 'static'

else:

    STATICFILES_DIRS = [
        BASE_DIR / 'static'
    ]


MEDIA_URL = f'https://storage.googleapis.com/{BUCKET_NAME}/'
MEDIA_ROOT = f'gs://{BUCKET_NAME}/'

# MEDIA_URL = 'https://clubs.pes.edu/'
# MEDIA_ROOT = BASE_DIR / 'static/images/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'



CKEDITOR_CONFIGS = {
    'default': {
        # 'toolbar': 'full',
        'toolbar': 'Custom',
        'width': '100%',
        'height': '50vh',
        'toolbar_Custom': [
            ['Bold', 'Italic', 'Underline', 'Strike'],
            ['NumberedList', 'BulletedList', 'Outdent', 'Indent'],
            ['JustifyLeft', 'JustifyCenter', 'JustifyRight', 'JustifyBlock'],
            ['Link', 'Unlink'],
            ['Table'],
            ['SpecialChar'],
            ['Iframe'],
            ['Styles', 'Format'],
            ['TextColor', 'BGColor'],
            ['Maximize'],
            ['Source'],
            ['SelectAll', 'RemoveFormat', 'SpellChecker'],
            ['Button', 'ImageButton'],
            ['FontSize', 'Font'],
            ['Image'],  # Add this line to include the Image button in the toolbar
        ],
        'extraPlugins': ','.join(['image']),  # Include the 'image' plugin
        'removePlugins': 'image2',  # Remove the 'image2' plugin (older version)
        'allowedContent': True,  # Allow all content (including images)
        # 'filebrowserImageUploadUrl': 'https://storage.googleapis.com/focus-copilot-438910-g0.appspot.com/events/bharat-unlished/',  # Specify the URL for image uploads
    }
}


# Default session cookie age (4 hours)
SESSION_COOKIE_AGE = 60 * 60 * 4

# Longer session cookie age for "Remember me" (30 days)
SESSION_COOKIE_AGE_REMEMBER_ME = 60 * 60 * 24 * 30